baseURL = 'http://status.aaronbieber.com/'
languageCode = 'en-us'
title = "Aaron's Status"
theme = 'status'
summaryLength = 10

[markup]
[markup.tableOfContents]
startLevel = 3
endLevel = 4

[outputs]
home = ["html", "rss", "tweets"]

[outputFormats]
[outputFormats.rss]
mediatype = "application/rss"
rel = "index"
baseName = "index"
[outputFormats.tweets]
mediatype = "application/rss"
baseName = "tweets"
